- project:
    templates:
      - openstack-python-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - openstack-python35-jobs
      - openstack-python36-jobs
      - release-notes-jobs-python3
